#!/usr/bin/env bash
set -euo pipefail

exec nvim +"autocmd VimEnter * ++once lua vim.schedule(function() local telescope = require('telescope') pcall(telescope.load_extension, 'file_browser') telescope.extensions.file_browser.file_browser({ path = vim.loop.cwd(), cwd = vim.loop.cwd(), hidden = true, respect_gitignore = false, grouped = true, initial_mode = 'insert' }) end)"
