[[session]]
name = "terminal-local"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_terminal"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris"

[[session]]
name = "vim-file"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session --find-files"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris"

[[session]]
name = "tds-oc"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_tds"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris"

[[session]]
name = "ssh-connect"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_ssh"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris"

[[session]]
name = "notes-new"
path = "~/Obsidian/engineer/0 Inbox/"
startup_command = "EDITOR=/home/boris/.config/sesh/scripts/nvim_file_session onn"
preview_command = "eza -alg --color=always --group-directories-first -- '/home/boris/Obsidian/engineer/0 Inbox'"

[[session]]
name = "notes-vault"
path = "~/Obsidian/engineer/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris/Obsidian/engineer"

# open the file manager
[[session]]
name = "files-downloads"
path = "~/Downloads"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_browser"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris/Downloads"

[[session]]
name = "cfg-dotfiles"
path = "~/dotfiles/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris/dotfiles"

[[session]]
name = "cfg-opencode"
path = "~/.config/opencode/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.config/opencode/config.json"
preview_command = "sed '/CONTEXT7_API_KEY/d' /home/boris/.config/opencode/config.json"

[[session]]
name = "cfg-zshrc"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.zshrc"
preview_command = "cat -- /home/boris/.zshrc"

[[session]]
name = "cfg-nvim"
path = "~/.config/nvim/lua/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"
preview_command = "eza -alg --color=always --group-directories-first -- /home/boris/.config/nvim/lua"

[[session]]
name = "cfg-tmux"
path = "~/.config/tmux/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.config/tmux/tmux.conf"
preview_command = "cat -- /home/boris/.config/tmux/tmux.conf"

[[session]]
name = "cfg-hypr"
path = "~/.config/hypr/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.config/hypr/hyprland.conf"
preview_command = "cat -- /home/boris/.config/hypr/hyprland.conf"

[[session]]
name = "cfg-ssh"
path = "~/.ssh/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.ssh/config"
preview_command = "cat -- /home/boris/.ssh/config"

[[session]]
name = "cfg-sesh"
path = "~/.config/sesh/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_session /home/boris/.config/sesh/sesh.toml"
preview_command = "cat -- /home/boris/.config/sesh/sesh.toml"

# run a script to startup a node project
# [[session]]
# path = "~/c/joshmedeski.com"
# startup_script = "~/.config/sesh/scripts/node_dev"
